config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  mount StripeEvent::Engine, at: '/webhooks'
  root 'dashboards#index'
  resources :supports do
    member do
      get :get_specific_chat
    end
    collection do
      get :update_ticket_status
    end
  end
  resources :sub_admins do
    member do
      get :deactive_admin
      get :active_admin
    end
  end
  resources :school_pins do
    collection do
    get 'get_school_pins'
  end
end
  resources :dashboards do
    post :index
    collection do
      get :notification_page
    end
  end
  resources :support_closers do
    member do
      get :active_account
      get :deactive_account
    end
  end
  resources :guidelines do
    collection do
      post :job_list
      get :job_lists
      delete :job_list
      get :contact_us
      get :privacy_policy
      get :deletion
    end
  end
  get '/delete_job_list/:id', to: 'guidelines#delete_job_list', as: :delete_job_list
  post 'privacy_policy/:permalink', to: 'guidelines#create'
   resources :users_data do
    collection do
      get :buy_vacant_land
      post :buy_vacant_land
      get :buy_house
      post :buy_house
      get :buy_condo
      post :buy_condo
      get :sell_vacant_land
      post :sell_vacant_land
      get :sell_house
      post :sell_house
      get :sell_condo
      post :sell_condo
      get :user_info
      get :dream_address
      get :property_profile
    end
  end
  resources :users_lists do
    member do
      get :active_account
      get :deactive_account
      get :user_profile
    end
  end
  devise_for :admins,
  controllers: {
    passwords: 'admins/passwords'
  }
  get '/sp_active_account/:id', to: 'support_closers#active_user', as: 'sp_active_account'
  get '/sp_deactive_account/:id', to: 'support_closers#deactive_user',as: 'sp_deactive_account'
  get '/privacy_policy/:permalink', to: 'guidelines#guidelines', as: 'privacy_policy'

  namespace :api do
    namespace :v1 do

      post '/login', to: 'sessions#login'
      post '/logout', to: 'sessions#logout'

      post '/signup', to: 'registrations#create'
      post '/register_user', to: 'registrations#complete_registration'
      post '/verify_otp', to: 'registrations#verify_otp'
      post '/verify_otp/resend_otp', to: 'registrations#resend_otp'

      post '/forgot_password/email', to: 'forgot_password#forgot_password_through_email'
      post '/forgot_password/phone', to: 'forgot_password#forgot_password_through_phone'
      post '/reset_password/email', to: 'forgot_password#reset_password_with_email'
      post '/reset_password/phone', to: 'forgot_password#reset_password_with_phone'

      get '/show_profile', to: 'users#show_profile'
      get '/show_other_user_profile', to: 'users#show_other_user_profile'
      get '/profile_visitor_list', to: 'users#profile_visitor_list'
      put '/update_profile', to: 'users#update_profile'
      delete '/delete_account', to: 'users#delete_account'
      get '/search_support_closers', to: 'users#search_support_closers'
      get '/top_support_closers', to: 'users#get_highest_rated_support_closers'
      get 'blocked_users', to: 'users#blocked_users'
      get 'unblocked_users', to: 'users#unblocked_users'
      post 'block_unblock_user', to: 'users#block_unblock_user'
      post 'report_unreport_user', to: 'users#report_unreport_user'
      get 'reported_users', to: 'users#reported_users'
      put '/update_location', to: 'users#update_location'
      # post '/get_school', to: 'users#get_school'
      # post '/get_school_pins', to: 'users#get_school_pins'

      post '/create_card', to: 'payments#create_card'
      get '/get_packages', to: 'payments#get_packages'
      post '/create_package', to: 'payments#create_package'
      post '/create_subscription_on_card', to: 'payments#create_subscription_on_card'
      post '/create_subscription_on_digital_wallet', to: 'payments#create_subscription_on_digital_wallet'
      post '/cancel_subscription', to: 'payments#cancel_subscription'
      get '/get_subscription', to: 'payments#get_subscription'
      get '/get_subscription_history', to: 'payments#get_subscription_history'
      get '/get_card', to: 'payments#get_card'
      get '/get_all_cards', to: 'payments#get_all_cards'
      get '/get_default_card', to: 'payments#get_default_card'
      put '/set_default_card', to: 'payments#set_default_card'
      put '/update_card', to: 'payments#update_card'
      delete '/delete_card', to: 'payments#destroy_card'

      get '/mark_as_read', to: 'notifications#mark_as_read'
      get '/get_user_notifications', to: 'notifications#get_user_notifications'
      delete '/delete_notification', to: 'notifications#delete_notification'

      get '/tickets', to: 'supports#get_tickets'
      post '/tickets', to: 'supports#create_ticket'

      post '/social_login', to: 'social_logins#social_login'
      get '/static_page/:permalink', to: 'static_pages#static_page'
      post '/active', to: 'users_lists#index'

      get '/show_current_user_setting', to: 'user_settings#show'
      put '/update_current_user_setting', to: 'user_settings#update'

      resources :properties, only: [:index, :show, :create, :update, :destroy] do
        collection do
          get :detail_options
          get :matching_properties
          get :buy_properties_listing
          get :find_in_circle
          get :find_in_polygon
          get :find_by_zip_code
          get :details_by_property_id
          # get :recent_properties
          # get :matching_property
          # get :matching_dream_address
        end
      end

      resources :dream_addresses, only: [:index, :create, :destroy]
      # resources :dream_addresses, only: [:index, :create, :destroy] do
      #   collection do
      #     post :fetch_property
      #     post 'fetch_user'
      #   end
      # end

      resources :saved_searches, except: [:new, :edit]
      resources :bookmarks, only: [:index, :create, :destroy]

      resources :user_preferences, only: [:index, :create] do
        collection do
          get '/potential_buyers', to: 'user_preferences#get_potential_buyer_preferences'
        end
      end
      resources :reviews, only: [:create] do
        collection do
          get :get_reviews
        end
      end
      resources :searched_addresses, only: [:create] do
        collection do
          get :get_users
        end
      end
      resources :support_conversations do
        collection do
          post :create_message
          post :get_messages
        end
      end
      resources :reporting do
        collection do
          post 'report_conversation'
        end
      end
      resources :conversations, only: [:create, :index, :destroy] do
        collection do
          post :check_conversation_between_users
          post :check_conversation_blocked_status
          post :read_messages
        end
      end
      resources :messages, only: [:create, :destroy] do
        collection do
          post :get_messages
        end
      end

      get '/*a', to: 'api#not_found'
    end
  end

end

app/controllers/guidelines_controller.rb
class GuidelinesController < ApplicationController
  before_action :get_paper_trail, only: [:index,:create,:guidelines]
  before_action :get_page, only: [:index, :create, :guidelines]
  skip_before_action :authenticate_admin!, only: [:contact_us, :privacy_policy, :deletion]

  def index
  end

  def create
    @page.update(content: params[:content])
    render 'index'
  end

  def guidelines
    render 'index'
  end

  def contact_us
    file_path = Rails.root.join('public', 'contact_us.html')
    send_file file_path, type: 'text/html', disposition: 'inline'
  end 
  def privacy_policy
    file_path = Rails.root.join('public', 'privacy_policy.html')
    send_file file_path, type: 'text/html', disposition: 'inline'
  end

  def deletion
    file_path = Rails.root.join('public', 'deletion.html')
    send_file file_path, type: 'text/html', disposition: 'inline'
  end

  def get_page
    @page = Page.find_by(permalink: params[:permalink].blank? ? "terms&condition" : params[:permalink])
  end

  def get_paper_trail
    @paper_trail =  PaperTrail::Version.where(item_type: "Page").order(created_at: :desc).limit(3)
  end

  def job_list
    @paper_trail = PaperTrail::Version.where(item_type: "JobList").order(created_at: :desc).limit(3)
    @job_list = JobList.new(title: params[:title])
    if @job_list.save
      redirect_to job_lists_guidelines_path()
    else
     redirect_to job_lists_guidelines_path
    end
  end 

  def job_lists
    @paper_trail = PaperTrail::Version.where(item_type: "JobList").order(created_at: :desc).limit(3)
    @job_lists = JobList.all.order(created_at: :desc)
  end
  def delete_job_list
    @job_list = JobList.find_by(id: params[:id])
    if @job_list.present?
      if @job_list.destroy
        redirect_to job_lists_guidelines_path
      end
    end
  end

end

app/helpers/guideline_helper.rb
module GuidelineHelper
  def privacy_policy_option_selected(params)
    params[:permalink]== "privacy_policy" ? "selected" : ""
  end

  def terms_and_condition_option_slected(params)
    params[:permalink] == "terms&condition" ? "selected" : ""
  end

  def faq_option_selected(params)
    params[:permalink] == "faq" ? "selected" : ""
  end

  def job_lists_option_selected(params)
    params[:action] == "job_lists"  ? "selected" : ""
  end
end

app/views/guidelines/_drop_down_mean.html.erb
<div class="dropdown mb-4">
  <select class="text dropdown-toggle input w-auto fs_5 fw_600" id="guideline_select">
    <option value="1" data-page="terms&condition" <%=  terms_and_condition_option_slected(params) %>>
      Terms & Condition
    </option>
    <option value="3" data-page="privacy_policy" <%= privacy_policy_option_selected(params) %>>
      Privacy Policy
    </option>
    <option value="2" data-page="faq" <%= faq_option_selected(params) %>>
      FAQ
    </option>
    <option value="4" data-page="job_list" <%= job_lists_option_selected(params) %>>
      Job List
    </option>
  </select>
</div>
<a id="guide_lines_1" href="<%= privacy_policy_path(permalink: "terms&condition") %>" hidden></a>
<a id="guide_lines_2" href="<%= privacy_policy_path(permalink: "faq") %>" hidden></a>
<a id="guide_lines_3" href="<%= privacy_policy_path(permalink: "privacy_policy") %>" hidden></a>
<a id="guide_lines_4" href="<%= job_lists_guidelines_path %>" hidden></a>

app/views/guidelines/_paper_trail_section.html.erb
<div class="date-section">
  <div class="btn_blk">
    <% if params[:action] != "job_lists" %>
      <button class="site_btn save_btn" type="button" id="submitbtnclick">Save</button>
      <button type="submit" id="customsavebutton" hidden></button>
      <%else%>
          <button class="site_btn save_btn pop_btn" data-popup="add_jobs">Add Job</button>
    <%end%>
  </div>
  <h3><%= Date.today.strftime("%B %d,%Y") %></h3>
  <p class="mb-2">Update Logs</p>
  <% @paper_trail.each do |record| %>
    <p class="fw_600 mb-2"><%= record.created_at.strftime("%d/%m/%Y") %> - <%= record.event %></p>
    <p><%= page_title(record.item_id) %></p>
    <hr class="hr">
  <% end %>
</div>

app/views/guidelines/index.html.erb
<main>
  <section id="account_section">
    <%= render 'shared/sidebar' %>
    <div id="guide_lines" class="main_side">
      <div id="top_header">
        <h1>Guidelines</h1>
        <%= render 'shared/header-side' %>
      </div>

      <div class="right-con-inner">
        <%= render 'drop_down_mean' %>
        <%= form_with do |f| %>
          <div class="row">
            <div class="col-lg-8">

              <div class="details" id="submitcontentfieldvalue" contenteditable="true">
                <%= @page.content %>
              </div>
              <%= f.hidden_field :content, id: "submitcontentfield" %>
              <%= f.hidden_field :permalink, id: "guidelinepagevalue" %>
            </div>
            <div class="col-lg-4">
              <%= render 'paper_trail_section' %>
            </div>
          </div>
        <% end %>

      </div>

    </div>
  </section>
</main>

app/views/guidelines/job_lists.html.erb
<section id="account_section">
  <%= render 'shared/sidebar' %>
  <div id="guide_lines" class="main_side">
    <div id="top_header">
      <h1>Guidelines</h1>
      <%= render 'shared/header-side' %>
    </div>
    <div class="right-con-inner">
      <%= render 'drop_down_mean' %>
      <div class="row">
        <div class="col-lg-8">
          <ul class="job_list">
            <%@job_lists.each do |job_list|%>
              <li id="title_of_job_<%= job_list.id%>">
                <div class="jobs"><%=job_list.title%></div>
                <div class="dropdown">
                  <div class="icon_blk dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= image_tag 'more.svg' %>
                  </div>
                  <ul class="remove dropdown-menu" aria-labelledby="dropdownMenuButton1 pressactivelink">
                    <li class="customjobclass" id="<%= job_list.id %>">
                      <%= link_to 'Remove', delete_job_list_path(id: job_list), class: "pressactivelink remove-job-list", remote: true, data: { job_id: job_list.id } %>
                    </li>
                  </ul>
                </div>
              </li>
            <%end%>
          </ul>
        </div>
        <div class="col-lg-4">
          <%= render 'paper_trail_section' %>
        </div>
      </div>
    </div>
    <section class="popup" data-popup="add_jobs">
      <div class="table_dv">
        <div class="table_cell">
          <div class="contain-fluid">
            <div class="row justify-content-center">
              <div class="col-lg-4 col-md-8 col-sm-10">
                <div class="_inner">
                  <%= form_with url: job_list_guidelines_path do |form| %>
                  <h4 class="heading">Add Job List</h4>
                  <h5>Up to 30 characters</h5>
                  <hr class="hr">
                  <%= form.text_area :title, class: "input",placeholder: 'Input Here',id:'myTextfield' %>
                  <div class="btn_blk modal_btn">
                    <%= link_to "cancel", job_lists_guidelines_path, class:"cancel", style: "margin-top: 15px;" %>
                    <button type="submit" class="save site_btn">Save</button>
                  </div>
                   <% end%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</section>
 <script>

$(document).ready(function() {
    var elem = $("#myTextfield");
    if (elem) {
        elem.keydown(function() {
            if (elem.val().length > 10)
                elem.val(elem.val().substr(0, 30));
        });
    }            
});
</script>