config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  mount StripeEvent::Engine, at: '/webhooks'
  root 'dashboards#index'
  resources :supports do
    member do
      get :get_specific_chat
    end
    collection do
      get :update_ticket_status
    end
  end
  resources :sub_admins do
    member do
      get :deactive_admin
      get :active_admin
    end
  end
  resources :school_pins do
    collection do
    get 'get_school_pins'
  end
end
  resources :dashboards do
    post :index
    collection do
      get :notification_page
    end
  end
  resources :support_closers do
    member do
      get :active_account
      get :deactive_account
    end
  end
  resources :guidelines do
    collection do
      post :job_list
      get :job_lists
      delete :job_list
      get :contact_us
      get :privacy_policy
      get :deletion
    end
  end
  get '/delete_job_list/:id', to: 'guidelines#delete_job_list', as: :delete_job_list
  post 'privacy_policy/:permalink', to: 'guidelines#create'
   resources :users_data do
    collection do
      get :buy_vacant_land
      post :buy_vacant_land
      get :buy_house
      post :buy_house
      get :buy_condo
      post :buy_condo
      get :sell_vacant_land
      post :sell_vacant_land
      get :sell_house
      post :sell_house
      get :sell_condo
      post :sell_condo
      get :user_info
      get :dream_address
      get :property_profile
    end
  end
  resources :users_lists do
    member do
      get :active_account
      get :deactive_account
      get :user_profile
    end
  end
  devise_for :admins,
  controllers: {
    passwords: 'admins/passwords'
  }
  get '/sp_active_account/:id', to: 'support_closers#active_user', as: 'sp_active_account'
  get '/sp_deactive_account/:id', to: 'support_closers#deactive_user',as: 'sp_deactive_account'
  get '/privacy_policy/:permalink', to: 'guidelines#guidelines', as: 'privacy_policy'

  namespace :api do
    namespace :v1 do

      post '/login', to: 'sessions#login'
      post '/logout', to: 'sessions#logout'

      post '/signup', to: 'registrations#create'
      post '/register_user', to: 'registrations#complete_registration'
      post '/verify_otp', to: 'registrations#verify_otp'
      post '/verify_otp/resend_otp', to: 'registrations#resend_otp'

      post '/forgot_password/email', to: 'forgot_password#forgot_password_through_email'
      post '/forgot_password/phone', to: 'forgot_password#forgot_password_through_phone'
      post '/reset_password/email', to: 'forgot_password#reset_password_with_email'
      post '/reset_password/phone', to: 'forgot_password#reset_password_with_phone'

      get '/show_profile', to: 'users#show_profile'
      get '/show_other_user_profile', to: 'users#show_other_user_profile'
      get '/profile_visitor_list', to: 'users#profile_visitor_list'
      put '/update_profile', to: 'users#update_profile'
      delete '/delete_account', to: 'users#delete_account'
      get '/search_support_closers', to: 'users#search_support_closers'
      get '/top_support_closers', to: 'users#get_highest_rated_support_closers'
      get 'blocked_users', to: 'users#blocked_users'
      get 'unblocked_users', to: 'users#unblocked_users'
      post 'block_unblock_user', to: 'users#block_unblock_user'
      post 'report_unreport_user', to: 'users#report_unreport_user'
      get 'reported_users', to: 'users#reported_users'
      put '/update_location', to: 'users#update_location'
      # post '/get_school', to: 'users#get_school'
      # post '/get_school_pins', to: 'users#get_school_pins'

      post '/create_card', to: 'payments#create_card'
      get '/get_packages', to: 'payments#get_packages'
      post '/create_package', to: 'payments#create_package'
      post '/create_subscription_on_card', to: 'payments#create_subscription_on_card'
      post '/create_subscription_on_digital_wallet', to: 'payments#create_subscription_on_digital_wallet'
      post '/cancel_subscription', to: 'payments#cancel_subscription'
      get '/get_subscription', to: 'payments#get_subscription'
      get '/get_subscription_history', to: 'payments#get_subscription_history'
      get '/get_card', to: 'payments#get_card'
      get '/get_all_cards', to: 'payments#get_all_cards'
      get '/get_default_card', to: 'payments#get_default_card'
      put '/set_default_card', to: 'payments#set_default_card'
      put '/update_card', to: 'payments#update_card'
      delete '/delete_card', to: 'payments#destroy_card'

      get '/mark_as_read', to: 'notifications#mark_as_read'
      get '/get_user_notifications', to: 'notifications#get_user_notifications'
      delete '/delete_notification', to: 'notifications#delete_notification'

      get '/tickets', to: 'supports#get_tickets'
      post '/tickets', to: 'supports#create_ticket'

      post '/social_login', to: 'social_logins#social_login'
      get '/static_page/:permalink', to: 'static_pages#static_page'
      post '/active', to: 'users_lists#index'

      get '/show_current_user_setting', to: 'user_settings#show'
      put '/update_current_user_setting', to: 'user_settings#update'

      resources :properties, only: [:index, :show, :create, :update, :destroy] do
        collection do
          get :detail_options
          get :matching_properties
          get :buy_properties_listing
          get :find_in_circle
          get :find_in_polygon
          get :find_by_zip_code
          get :details_by_property_id
          # get :recent_properties
          # get :matching_property
          # get :matching_dream_address
        end
      end

      resources :dream_addresses, only: [:index, :create, :destroy]
      # resources :dream_addresses, only: [:index, :create, :destroy] do
      #   collection do
      #     post :fetch_property
      #     post 'fetch_user'
      #   end
      # end

      resources :saved_searches, except: [:new, :edit]
      resources :bookmarks, only: [:index, :create, :destroy]

      resources :user_preferences, only: [:index, :create] do
        collection do
          get '/potential_buyers', to: 'user_preferences#get_potential_buyer_preferences'
        end
      end
      resources :reviews, only: [:create] do
        collection do
          get :get_reviews
        end
      end
      resources :searched_addresses, only: [:create] do
        collection do
          get :get_users
        end
      end
      resources :support_conversations do
        collection do
          post :create_message
          post :get_messages
        end
      end
      resources :reporting do
        collection do
          post 'report_conversation'
        end
      end
      resources :conversations, only: [:create, :index, :destroy] do
        collection do
          post :check_conversation_between_users
          post :check_conversation_blocked_status
          post :read_messages
        end
      end
      resources :messages, only: [:create, :destroy] do
        collection do
          post :get_messages
        end
      end

      get '/*a', to: 'api#not_found'
    end
  end

end

app/controllers/users_lists_controller.rb
class UsersListsController < ApplicationController
  require 'will_paginate/array'
  
  skip_before_action :authenticate_admin!
  def index
    notification = AdminNotification.find_by(id: params[:id])
    notification.update(read_at: Time.now) if notification.present?
  
    unless params[:search].blank?
      @all_users = User.all_users.custom_search(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    else
      @all_users = User.all_users.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    end
    response_to_method
  end

  def user_profile
    @user = User.find_by(id: params[:id])
  end

  def response_to_method
    respond_to do |format|
      format.html
      @all_users =  User.where(id: params[:checkbox_value].split(","))  if params[:checkbox_value].present?
      format.csv { send_data @all_users.to_csv }
    end
  end

  def active_account
    @user = User.find_by(id: params[:id])
      if @user.update(active: true)
        notification = AdminNotification.where("action ILIKE ?", "#{@user.full_name} is active")
        unless notification.present?
          AdminNotification.create(actor_id: Admin.admin.first.id,
                                recipient_id: @user.id, action: "#{@user.full_name} is active") if Admin&.admin.present?
        end
      redirect_to users_lists_path
    else
      redirect_to users_lists_path

    end
  end

  def deactive_account
     @user = User.find_by(id: params[:id])
      if @user.update(active: false)
        notification = AdminNotification.where("action ILIKE ?", "#{@user.full_name} is deactive")
        unless notification.present?
          AdminNotification.create(actor_id: Admin.admin.first.id,
                                recipient_id: @user.id, action: "#{@user.full_name} is deactive") if Admin&.admin.present?
        end
      redirect_to users_lists_path
    else
      redirect_to users_lists_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      AdminNotification.create(actor_id: Admin.admin.first.id,
                              recipient_id: @user.id, action: "New User Created") if Admin&.admin.present?
      redirect_to users_lists_path()
    else
      flash.alert = @user.errors.full_messages.join(', ')
      redirect_to users_lists_path()
    end
  end
  private

  def user_params
    params.permit(:full_name, :email, :password, :address,:description, :phone_number,
                  :user_type,:profile_type,:contacted_by_real_estate,:licensed_realtor)
  end

end

app/views/users_lists/index.html.erb
<main>
  <section id="account_section">
    <%= render 'shared/sidebar' %>
    <div id="subAdmins" class="main_side">
      <div id="top_header">
        <h1>User List</h1>
        <%= render 'shared/header-side' %>
      </div>
      <% if flash[:alert].present? %>
        <div id="flash-alert" class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
        <script>
          document.addEventListener('DOMContentLoaded', function() {
            setTimeout(function(){
              var flashAlert = document.getElementById('flash-alert');
              if (flashAlert) {
                flashAlert.style.opacity = '0';
                setTimeout(function() {
                  flashAlert.style.display = 'none';
                }, 5000);
              }
            }, 5000);
          });
        </script>
      <% end %>
      <div class="top_blk">
        <div class="row">
          <div class="col-6">
            <ul class="top_blk_filters">
              <li>
                <div class="dropdown">
                  <button class="filter text dropdown-toggle fs_5 fw_600" data-bs-toggle="dropdown">
                    <div class="img_blk">
                      <%= image_tag 'filter.svg', alt: '' %>
                   </div>
                    filters
                  </button>
                  <%= render 'shared/drop_down' %>
                </div>
              </li>
              <li>
                <%= form_for :sub_admin, :url => { :controller => 'users_lists', :action => 'index' }, :html => { :method => 'get', class: 'form_blk' } do |f| %>
                  <div class="icon_blk">
                    <%= image_tag 'search.svg' %>
                  </div>
                  <%= text_field_tag :search, nil, placeholder: 'Search', id: "csearchbtn", class: 'input', value: params[:search] %>
                  <input type="submit" id="searchformc" hidden>
                <% end %>
              </li>
              <% if @all_users.present? %>
                <li>
                  <button type="button" class="filter">
                    <div class="img_blk">
                      <%= image_tag 'csv-file-icon.svg' %>
                    </div>
                    <%= link_to "Download CSV", users_lists_path(format: 'csv', search: params[:search], page: params[:page], checkbox_value:""), id: "downloadbtncustom" %>
                  </button>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="btn_blk">
          <button type="button" class="pop_btn" data-popup="add_subadmin">
            <div class="people_blk">
              <%= image_tag 'addPerson.svg' %>
            </div>
            Add
          </button>
        </div>
      </div>

      <div class="table_blk mt-5 pt-3">
        <table>
          <thead>
          <tr>
            <th style="width:12.2rem">
              <div class="d-flex align-items-center">
                <input type="checkbox" class="me-2" id="selectedallcheckboxes">
                Select all
              </div>
            </th>
            <th style="width: 19rem;">
              Name/Email
            </th>
            <th style="width:15.1rem">
              Phone No.
            </th>
            <th style="width:12rem">
              Real State Agent
            </th>
            <th style="width:14rem">
              Address
            </th>
            <th style="width: 10rem">
              Status
            </th>
          </tr>
          </thead>
          <tbody>
          <% if @all_users.exists? %>
            <% @all_users.each do |user| %>
              <tr>
                <td>
                  <div class="d-flex align-items-center">
                    <input type="checkbox" name="selected_checkbox" class="me-3" id="<%= user.id%>">
                    <div class="img_blk">
                      <% if user.avatar.attached?%>
                        <%= image_tag(user.avatar.url, class: "round-image", style: "border-radius: 50%; width: 50px; height: 50px;") %>
                      <% else %>
                        <img src="/assets/default-profile.jpg" alt="" style="border-radius: 50%; width: 50px; height: 50px;">
                      <%end%>
                    </div>
                  </div>
                </td>
                <td class=" user_name" style="padding-right: 30px;">
                  <%= link_to user_profile_users_list_path(id: user) do %>
                    <p class="fw_500 mb-0">
                      <%= user.full_name %>
                    </p>
                    <p class="fw_400" style="color: #626262" style="color: #626262">
                      <%= user.email %>
                    </p>
                  <% end %>
                </td>
                <td style="padding-right: 30px;"><%= user.phone_number %></td>
                <td style="padding-right: 25px;"><%= user.contacted_by_real_estate ? 'Yes' : 'No' %></td>
                <td style="padding-right: 40px;"><%= user.address %></td>
                <td style="padding-right: 10px;">
                  <div class="d-flex align-items-center justify-content-between">
                    <p class="mb-0" id="active_user_<%= user.id %>" style="color:#93DF70;" <%= 'hidden' unless user.active %> >Active</p>
                    <p class="mb-0" id="deactive_user_<%= user.id %>" style="color:#df7074;" <%= 'hidden' if user.active %> >Disable
                      Account</p>
                    <div class="more_btn_blk" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                      <%= image_tag 'more.svg' %>
                    </div>
                    <ul class="remove dropdown-menu px-5" aria-labelledby="dropdownMenuButton1">
                      <li <%= 'hidden' unless user.active %> class="pressdeactivelinkwith_<%= user.id %>">
                        <%= link_to 'Disable account', deactive_account_users_list_path(id: user), class: "pressdeactivelink", id: user.id, :remote => true %>
                      </li>
                      <li <%= 'hidden' if user.active %> class="pressactivelinkwith_<%= user.id %>">
                        <%= link_to 'Active', active_account_users_list_path(id: user), id: user.id, class: "pressactivelink", remote: :true %>
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
      <%= render 'shared/pagination', data: @all_users %>
      <section class="popup" data-popup="add_subadmin">
        <div class="table_dv">
          <div class="table_cell">
            <div class="contain-fluid">
              <div class="row justify-content-center">
                <div class="col-lg-5 col-md-8 col-sm-10">
                  <div class="_inner">
                    <h4 class="heading">Add User</h4>
                    <h5>Personal Data</h5>
                    <hr class="hr">
                    <%= form_with model: @user, class:"sub_admin_form"  do |form| %>
                      <div class="form_blk d-flex align-items-center justify-content-between sub_admin_form">
                        <label for="">First Name</label>
                        <%if flash.alert.present? %>
                          <span>
                           <%= show_sub_admin_message(flash.alert,"Full name") %>
                          </span>
                        <% end %>
                        <%= form.text_field :full_name, class: "input", required: true %>
                      </div>
                      <div class="form_blk d-flex align-items-center justify-content-between">
                        <label for="">Profile Type</label>
                        <%if flash.alert.present? %>
                          <span>
                          <%= show_sub_admin_message(flash.alert,"Profile Type") %>
                          </span>
                        <% end %>
                        <%= form.select :profile_type, ["want_sell","want_buy"],{:include_blank => "Select from the option"}, {class: "input", required: true}%>
                      </div>
                      <div class="form_blk d-flex align-items-center justify-content-between">
                        <label for="">Contacted By Real State</label>
                        <%if flash.alert.present? %>
                          <span>
                          <%= show_sub_admin_message(flash.alert,"Contacted By Real Estate") %>
                          </span>
                        <% end %>
                        <%= form.select :contacted_by_real_estate, ["Yes","No"],{:include_blank => "Select from the option"}, {class: "input", required: true}%>
                      </div>
                      <div class="form_blk d-flex align-items-center justify-content-between">
                        <label for="">Licensed Realtor</label>
                        <%if flash.alert.present? %>
                          <span>
                          <%= show_sub_admin_message(flash.alert,"Licensed Realtor") %>
                          </span>
                        <% end %>
                        <%= form.select :licensed_realtor, ["Yes","No"],{:include_blank => "Select from the option"}, {class: "input", required: true}%>
                      </div>
                      <div class="form_blk d-flex align-items-center justify-content-between">
                        <label for="">User Type</label>
                        <%if flash.alert.present? %>
                          <span>
                          <%= show_sub_admin_message(flash.alert,"User Type") %>
                          </span>
                        <% end %>
                        <%= form.select :user_type, User.user_types.keys,{:include_blank => "Select from the option"}, {class: "input", required: true} %>
                      </div>
                      <div class="form_blk d-flex align-items-center justify-content-between">
                        <label for="">Address</label>
                        <%if flash.alert.present? %>
                          <span>
                          <%= show_sub_admin_message(flash.alert,"Address") %>
                          </span>
                        <% end %>
                        <%= form.text_field :address, class: "input", required: true %>
                      </div>
                      <h5>Account Information</h5>
                      <hr class="hr">
                      <div class="form_blk d-flex align-items-center justify-content-between">
                        <label for="">Email Address</label>
                        <%if flash.alert.present? %>
                          <span>
                          <%= show_sub_admin_message(flash.alert,"Email") %>
                          </span>
                        <% end %>
                        <%= form.text_field :email, class: "input", required: true %>
                      </div>
                      <div class="form_blk d-flex align-items-center justify-content-between">
                        <label for="">Phone Number</label>
                        <%if flash.alert.present? %>
                          <span>
                          <%= show_sub_admin_message(flash.alert,"Phone number") %>
                          </span>
                        <% end %>
                        <%= form.text_field :phone_number, class: "input", required: true %>
                      </div>
                      <div class="form_blk d-flex align-items-center justify-content-between">
                        <label for="">Temporary Password</label>
                        <%if flash.alert.present? %>
                          <span>
                          <%= show_sub_admin_message(flash.alert,"Password") %>
                          </span>
                        <% end %>
                        <%= form.text_field :password, class: "input", required: true %>
                      </div>
                      <div class="btn_blk modal_btn">
                        <%= link_to "Cancel", users_lists_path, class:"cancel", style: "margin-top: 15px;"%>
                        <button type="submit" class="save site_btn">Save</button>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </section>
</main>

app/views/users_lists/user_profile.html.erb
<section id="account_section">
  <%= render 'shared/sidebar' %>
  <div id="profile" class="main_side">
    <div id="top_header">
      <h1>User Profile</h1>
      <%= render 'shared/header-side' %>
    </div>
    <div class="profile_banner">
      <div class="inner text-center">
        <div class="ico fill round">
            <%= image_tag @user&.avatar&.attached? ? @user&.avatar&.url : "", alt: "No image provided" %>
        </div>
        <div class="txt">
          <h5><%= @user&.full_name %></h5>
          <p><a href="mailto:<%= @user&.email %>"><%= @user&.email %></a></p>
          <p><a href="tel:<%=@user&.phone_number %>"><%= @user&.phone_number %></a></p>
          <p><%= @user&.address %></p>
        </div>
      </div>
    </div>
    <ul class="nav tab_blk text-center">
      <li>
        <a href="#DreamAddress" data-bs-toggle="tab" class="active">Dream Address</a>
      </li>
      <li>
        <a href="#BuyingPreference" data-bs-toggle="tab">Buying Preference</a>
      </li>
      <li>
        <a href="#SellingLists" data-bs-toggle="tab">Selling Lists</a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane fade show active" id="DreamAddress">
        <h3>User’s Dream Addresses</h3>
        <ul class="view_map_blk fs_5">
          <% @user&.dream_addresses.each do |record| %>
            <li>
            <div class="ico fill">
              <%= image_tag 'loginbg.jpg', alt: "No image " %>
            </div>
            <div class="txt">
              <p class="fw_600"><%= record.location %></p>
            </div>
            <div class="btn_blk">
              <a href="https://www.google.com/maps/dir//<%=record.latitude %>,<%= record.longitude%>/@<%=record.latitude %>,<%= record.longitude%>z" class="site_btn text text-decoration-underline" target="_blank">View in map</a>
            </div>
          </li>
          <%end%>
        </ul>
      </div>
      <div class="tab-pane fade" id="BuyingPreference">
        <h3>User’s Buying Preference</h3>
        <table class="list_table w-100">
          <tbody>
          <tr>
            <td>Budget</td>
            <td class="fw_600"><%= @user.user_preference&.price.is_a?(Hash) ? "#{ @user.user_preference&.price['min'] } to #{ @user.user_preference&.price['max'] }" : "No preference" %></td>
          </tr>
          <tr>
            <td>Bedrooms</td>
            <td class="fw_600"><%= @user.user_preference&.bed_rooms.is_a?(Hash) ? "#{ @user.user_preference&.bed_rooms['min'] } to #{ @user.user_preference&.bed_rooms['max'] }" : "No preference" %></td>
          </tr>
          <tr>
            <td>Bathrooms</td>
            <td class="fw_600"><%= @user.user_preference&.bath_rooms.is_a?(Hash) ? "#{ @user.user_preference&.bath_rooms['min'] } to #{ @user.user_preference&.bath_rooms['max'] }" : "No preference" %></td>
          </tr>
          <tr>
            <td>Property Type</td>
            <td class="fw_600"><%= @user.user_preference&.property_type %></td>
          </tr>
          <tr>
            <td>Property Styles</td>
            <td class="fw_600"><%= ([*@user.user_preference&.house_style] + [*@user.user_preference&.condo_style]).join(', ') %></td>
          </tr>
          <tr>
            <td>Min Lot Forntage</td>
            <td class="fw_600"><%= @user.user_preference&.lot_frontage.is_a?(Hash) ? "#{@user.user_preference&.lot_frontage['min']} #{@user.user_preference&.lot_frontage_unit}" : 'No preference' %></td>
          </tr>
          <tr>
            <td>Lot Size (<%= @user.user_preference&.lot_size_unit%>)</td>
            <td class="fw_600"><%= @user.user_preference&.lot_size.is_a?(Hash) ? "#{ @user.user_preference&.lot_size['min'] } to #{ @user.user_preference&.lot_size['max'] }" : "No preference" %></td>
          </tr>
          <tr>
            <td>Parking Spots Req.</td>
            <td class="fw_600"><%= @user.user_preference&.garage_spaces.is_a?(Hash) ? @user.user_preference&.garage_spaces['min'] : 'No preference' %></td>
          </tr>
          <tr>
            <td>Balcony</td>
            <td class="fw_600"><%= @user.user_preference&.balcony&.join(', ') || 'No preference' %></td>
          </tr>
          <tr>
            <td>Security</td>
            <td class="fw_600"><%= @user.user_preference&.security&.join(', ') || 'No preference'%></td>
          </tr>
          <tr>
            <td>Laundry</td>
            <td class="fw_600"><%= @user.user_preference&.laundry&.join(', ') || 'No preference'%></td>
          </tr>
          <tr>
            <td>Max Age</td>
            <td class="fw_600"><%= @user.user_preference&.max_age%></td>
          </tr>
          </tbody>
        </table>
        <div class="fig"><img src="assets/images/no_input_box.png" alt=""></div>
      </div>
      <div class="tab-pane fade" id="SellingLists">
        <h3>User’s Selling Lists</h3>
        <div class="dropdown profile_dropdown">
          <button class="site_btn text dropdown-toggle chevron fs_5 fw_600" data-bs-toggle="dropdown">House</button>
          <ul class="dropdown-menu">
            <li><button type="button">House</button></li>
            <li><button type="button">Condo</button></li>
            <li><button type="button">Vacant Land</button></li>
          </ul>
        </div>
        <script>
          $(function(){
              $(document).on("click", ".profile_dropdown > ul > li > button", function(){
                  let text = $(this).text();
                  $(this).parents(".profile_dropdown").find(".site_btn").html(text);
                  if (text == "House")
                  {
                      $("#hosue").attr('hidden',false);
                      $("#SellingLists1").attr('hidden',true);
                      $("#SellingLists2").attr('hidden',true);
                  }
                  else if(text == "Condo")
                  {
                      $("#hosue").attr('hidden',true);
                      $("#SellingLists1").attr('hidden',false);
                      $("#SellingLists2").attr('hidden',true);

                  }
                  else if(text == "Vacant Land") {
                      $("#hosue").attr('hidden', true);
                      $("#SellingLists1").attr('hidden', true);
                      $("#SellingLists2").attr('hidden', false);
                  }

              })
          })
        </script>

        <ul class="home_map_blk fs_5", id= 'hosue'>
          <% get_house_property_list(@user.id).each do |property| %>
          <li>
            <div class="ico fill"> <%= image_tag property.images.attached? ? property&.images&.first.url : "" %></div>
            <div class="txt">
              <%= link_to property_profile_users_data_path(id: property) do %>
              <h5><%= property.title%></h5>
              <%end%>
              <p class="fs_6"><%= property&.city%> <%= property&.country%> </p>
            </div>

          </li>
          <%end%>
        </ul>
        <ul class="home_map_blk fs_5", id= 'SellingLists1' hidden>
          <% get_condo_property_list(@user.id).each do |property| %>
          <li>
            <div class="ico fill">
              <%= image_tag property.images.attached? ? property&.images&.first.url : "" %></div>
            <div class="txt">
              <%= link_to property_profile_users_data_path(id: property) do %>
              <h5><%= property.title%></h5>
              <%end%>
              <p class="fs_6"><%= property&.city%> <%= property&.country%> </p>
            </div>

          </li>
          <%end%>
        </ul>
        <ul class="home_map_blk fs_5", id= 'SellingLists2' hidden>
          <% get_vacant_land_property_list(@user.id).each do |property| %>
          <li>
            <div class="ico fill">
              <%= image_tag property.images.attached? ? property&.images&.first.url : "" %></div>
            <div class="txt">
              <%= link_to property_profile_users_data_path(id: property) do %>
              <h5><%= property.title%></h5>
              <%end%>
              <p class="fs_6"><%= property&.city%> <%= property&.country%> </p>
            </div>
          </li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</section>