config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  mount StripeEvent::Engine, at: '/webhooks'
  root 'dashboards#index'
  resources :supports do
    member do
      get :get_specific_chat
    end
    collection do
      get :update_ticket_status
    end
  end
  resources :sub_admins do
    member do
      get :deactive_admin
      get :active_admin
    end
  end
  resources :school_pins do
    collection do
    get 'get_school_pins'
  end
end
  resources :dashboards do
    post :index
    collection do
      get :notification_page
    end
  end
  resources :support_closers do
    member do
      get :active_account
      get :deactive_account
    end
  end
  resources :guidelines do
    collection do
      post :job_list
      get :job_lists
      delete :job_list
      get :contact_us
      get :privacy_policy
      get :deletion
    end
  end
  get '/delete_job_list/:id', to: 'guidelines#delete_job_list', as: :delete_job_list
  post 'privacy_policy/:permalink', to: 'guidelines#create'
   resources :users_data do
    collection do
      get :buy_vacant_land
      post :buy_vacant_land
      get :buy_house
      post :buy_house
      get :buy_condo
      post :buy_condo
      get :sell_vacant_land
      post :sell_vacant_land
      get :sell_house
      post :sell_house
      get :sell_condo
      post :sell_condo
      get :user_info
      get :dream_address
      get :property_profile
    end
  end
  resources :users_lists do
    member do
      get :active_account
      get :deactive_account
      get :user_profile
    end
  end
  devise_for :admins,
  controllers: {
    passwords: 'admins/passwords'
  }
  get '/sp_active_account/:id', to: 'support_closers#active_user', as: 'sp_active_account'
  get '/sp_deactive_account/:id', to: 'support_closers#deactive_user',as: 'sp_deactive_account'
  get '/privacy_policy/:permalink', to: 'guidelines#guidelines', as: 'privacy_policy'

  namespace :api do
    namespace :v1 do

      post '/login', to: 'sessions#login'
      post '/logout', to: 'sessions#logout'

      post '/signup', to: 'registrations#create'
      post '/register_user', to: 'registrations#complete_registration'
      post '/verify_otp', to: 'registrations#verify_otp'
      post '/verify_otp/resend_otp', to: 'registrations#resend_otp'

      post '/forgot_password/email', to: 'forgot_password#forgot_password_through_email'
      post '/forgot_password/phone', to: 'forgot_password#forgot_password_through_phone'
      post '/reset_password/email', to: 'forgot_password#reset_password_with_email'
      post '/reset_password/phone', to: 'forgot_password#reset_password_with_phone'

      get '/show_profile', to: 'users#show_profile'
      get '/show_other_user_profile', to: 'users#show_other_user_profile'
      get '/profile_visitor_list', to: 'users#profile_visitor_list'
      put '/update_profile', to: 'users#update_profile'
      delete '/delete_account', to: 'users#delete_account'
      get '/search_support_closers', to: 'users#search_support_closers'
      get '/top_support_closers', to: 'users#get_highest_rated_support_closers'
      get 'blocked_users', to: 'users#blocked_users'
      get 'unblocked_users', to: 'users#unblocked_users'
      post 'block_unblock_user', to: 'users#block_unblock_user'
      post 'report_unreport_user', to: 'users#report_unreport_user'
      get 'reported_users', to: 'users#reported_users'
      put '/update_location', to: 'users#update_location'
      # post '/get_school', to: 'users#get_school'
      # post '/get_school_pins', to: 'users#get_school_pins'

      post '/create_card', to: 'payments#create_card'
      get '/get_packages', to: 'payments#get_packages'
      post '/create_package', to: 'payments#create_package'
      post '/create_subscription_on_card', to: 'payments#create_subscription_on_card'
      post '/create_subscription_on_digital_wallet', to: 'payments#create_subscription_on_digital_wallet'
      post '/cancel_subscription', to: 'payments#cancel_subscription'
      get '/get_subscription', to: 'payments#get_subscription'
      get '/get_subscription_history', to: 'payments#get_subscription_history'
      get '/get_card', to: 'payments#get_card'
      get '/get_all_cards', to: 'payments#get_all_cards'
      get '/get_default_card', to: 'payments#get_default_card'
      put '/set_default_card', to: 'payments#set_default_card'
      put '/update_card', to: 'payments#update_card'
      delete '/delete_card', to: 'payments#destroy_card'

      get '/mark_as_read', to: 'notifications#mark_as_read'
      get '/get_user_notifications', to: 'notifications#get_user_notifications'
      delete '/delete_notification', to: 'notifications#delete_notification'

      get '/tickets', to: 'supports#get_tickets'
      post '/tickets', to: 'supports#create_ticket'

      post '/social_login', to: 'social_logins#social_login'
      get '/static_page/:permalink', to: 'static_pages#static_page'
      post '/active', to: 'users_lists#index'

      get '/show_current_user_setting', to: 'user_settings#show'
      put '/update_current_user_setting', to: 'user_settings#update'

      resources :properties, only: [:index, :show, :create, :update, :destroy] do
        collection do
          get :detail_options
          get :matching_properties
          get :buy_properties_listing
          get :find_in_circle
          get :find_in_polygon
          get :find_by_zip_code
          get :details_by_property_id
          # get :recent_properties
          # get :matching_property
          # get :matching_dream_address
        end
      end

      resources :dream_addresses, only: [:index, :create, :destroy]
      # resources :dream_addresses, only: [:index, :create, :destroy] do
      #   collection do
      #     post :fetch_property
      #     post 'fetch_user'
      #   end
      # end

      resources :saved_searches, except: [:new, :edit]
      resources :bookmarks, only: [:index, :create, :destroy]

      resources :user_preferences, only: [:index, :create] do
        collection do
          get '/potential_buyers', to: 'user_preferences#get_potential_buyer_preferences'
        end
      end
      resources :reviews, only: [:create] do
        collection do
          get :get_reviews
        end
      end
      resources :searched_addresses, only: [:create] do
        collection do
          get :get_users
        end
      end
      resources :support_conversations do
        collection do
          post :create_message
          post :get_messages
        end
      end
      resources :reporting do
        collection do
          post 'report_conversation'
        end
      end
      resources :conversations, only: [:create, :index, :destroy] do
        collection do
          post :check_conversation_between_users
          post :check_conversation_blocked_status
          post :read_messages
        end
      end
      resources :messages, only: [:create, :destroy] do
        collection do
          post :get_messages
        end
      end

      get '/*a', to: 'api#not_found'
    end
  end

end

app/views/shared/_drop_down.html.erb
<ul class="dropdown-menu">
  <li><%= link_to "All Data", users_data_path %></li>
  <li><%= link_to "User's Info", user_info_users_data_path %></li>
  <li><%= link_to "Dream Address",dream_address_users_data_path %></li>
  <li class="dropdown dropend">
    <button type="button">I Want to Buy</button>
    <ul class="dropdown-menu dropdown-submenu">
      <li>
        <%= link_to "House", buy_house_users_data_path%>
      </li>
      <li>
        <%= link_to "Condo", buy_condo_users_data_path %>
      </li>
      <li>
        <%= link_to "Vacant Land",buy_vacant_land_users_data_path%>
      </li>
    </ul>
  </li>
  <li class="dropdown dropend">
    <button type="button">I Want to Sell</button>
    <ul class="dropdown-menu dropdown-submenu">
      <li>
        <%= link_to "House", sell_house_users_data_path%>
      </li>
      <li>
        <%= link_to "Condo", sell_condo_users_data_path %>
      </li>
      <li>
        <%= link_to "Vacant Land",sell_vacant_land_users_data_path%>
      </li>
    </ul>
  </li>
</ul>

app/views/shared/_error_success_messages.html.erb
<div id="error-message">
  <p style="position:absolute; left:7%; font-weight:600; margin-top:-30px;"><%= notice %></p>
</div>

<% if flash[:success_alert].present? %>
  <div id="notice-message"><p style="position:absolute; left:7%; font-weight:600; margin-top:-30px;"><%= flash[:success_alert] %></p></div>
<%end%>

<script type="text/javascript">
	setTimeout(function() {
  $('#error-message').hide();
}, 5000);

setTimeout(function() {
  $('#notice-message').hide();
}, 5000);

</script>

app/views/shared/_footer.html.erb
<!-- Main Js -->
<script src="assets/js/main.js"></script>

app/views/shared/_header-side.html.erb
<div class="header_side">
  <!-- <div class="form_blk">
    <%#= image_tag 'icon-search.svg' %>
    <input type="text" name="" id="" class="input" placeholder="Search">
  </div> -->
  <%= link_to notification_page_dashboards_path, class: 'noti_btn input' do %>
    <%= image_tag 'icon-bell.svg' %>
    <span><%= AdminNotification.where(read_at:nil).count%></span>
  <% end %>
  <%= button_to "Logout", destroy_admin_session_path, method: :delete, class: "noti_btn input fw-bold px-5" %>
  </button>
</div>

app/views/shared/_pagination.html.erb
<div class="paginate_sec">
  <% if data.total_entries > 0 %>
    <p>Showing <%= data.offset_value + 1 %> to <%= [data.offset_value + data.length, data.total_entries].min %> of <%= data.total_entries %> entries</p>
    <div class="pagination">
      <%= will_paginate data, container: false, page_links: true, inner_window: 1, outer_window: -1, previous_label: "< Previous", next_label: "Next >" %>
    </div>
  <% else %>
    <p>No entries found</p>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<aside id="sidebar">
  <div class="inside">
    <div class="logo_blk">
      <div class="logo">
        <%= link_to dashboards_path do %>
        <%= image_tag 'logo_long.svg', alt: 'icon' %>
        <%end%>
      </div>
    </div>
    <ul>
      <li>
        <%= link_to 'Dashboard', dashboards_path, class: "#{check_controller('dashboards')}" %>
      </li>
      <li>
        <%= link_to "User's List", users_lists_path, class: "#{check_controller('users_lists')}" %>
      </li>
      <li>
        <%= link_to "User's All Data", users_data_path, class: "#{check_controller('users_data')}" %>
      </li>
      <li>
        <%= link_to "Support Closer's lists", support_closers_path, class: "#{check_controller('support_closers')}" %>
      </li>
      <li>
        <%= link_to 'Sub Admins', sub_admins_path, class: "#{check_controller('sub_admins')}" %>
      </li>
      <li>
        <%= link_to 'School Pin', school_pins_path, class: "#{check_controller('school_pins')}" %>
      </li>
      <li>
        <%= link_to 'Support',  supports_path, class: "#{check_controller('supports')}" %>
      </li>
      <li>
        <%= link_to 'Guidelines', guidelines_path, class: "#{check_controller('guidelines')}" %>
      </li>
    </ul>
  </div>
</aside>
      <!-- sidebar -->

app/views/shared/_site-master.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="title" content="Housibly">
<meta name="description" content="Housibly Description">
<meta property="og:type" content="website">
<meta property="og:url" content="index.php">
<meta property="og:title" content="Housibly">
<meta property="og:description" content="Housibly Description">
<meta property="og:image" content="assets/images/thumbnail.jpg">
<meta property="twitter:card" content="thumbnail">
<meta property="twitter:url" content="index.php">
<meta property="twitter:title" content="Housibly">
<meta property="twitter:description" content="Housibly Description">
<meta property="twitter:image" content="assets/images/thumbnail.jpg">

<!-- Css Files -->
<!--<link rel="stylesheet" href="assets/css/bootstrap.min.css?<?php echo time(); ?>">-->
<!--<link rel="stylesheet" href="assets/css/app.min.css?<?php echo time(); ?>">-->
<!--<link rel="stylesheet" href="assets/css/datepicker.min.css?<?php echo time(); ?>">-->

<!-- JS Files -->
<!--<script src="assets/js/jquery.min.js?<?php echo time(); ?>"></script>-->
<!--<script src="assets/js/bootstrap.bundle.min.js?<?php echo time(); ?>"></script>-->
<!--<script src="assets/js/k_datepicker.min.js?<?php echo time(); ?>"></script>-->

<!-- Favicon -->
<!--<link type="image/png" rel="icon" href="assets/images/favicon.png">-->

app/views/shared/footer.html.erb
<!-- Main Js -->
<script src="assets/js/main.js"></script>

app/views/shared/header-side.html.erb
<div class="header_side">
    <div class="form_blk">
        <img src="assets/images/icon-search.svg" alt="">
        <input type="text" name="" id="" class="input" placeholder="Search">
    </div>
    <button type="button" class="noti_btn input">
        <img src="assets/images/icon-bell.svg" alt="">
        <span>7</span>
    </button>
</div>

app/views/shared/pagination.html.erb
<div class="paginate_sec">
    <p>Showing 1 to 7 of 200 entries</p>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page_item disable me-4">
                <a class="page_link" href="#" aria-label="Previous">
                    <div class="icon_blk me-2">
                        <img src="assets/images/paginateLeftArrow.svg" aria-hidden="true" alt="icon">
                    </div>
                    Previous
                </a>
            </li>
            <li class="page_no "><a class="" href="#">1</a></li>
            <li class="page_no"><a class="" href="#">2</a></li>
            <li class="page_no"><a class="" href="#">3</a></li>
            <li class="page_item ms-4">
                <a class="page_link fw_600" href="#" aria-label="Previous">
                    Next
                    <div class="icon_blk ms-2">
                        <img src="assets/images/paginateRightArrow.svg" aria-hidden="true" alt="icon">
                    </div>
                </a>
            </li>
        </ul>
    </nav>
</div>

app/views/shared/site-master.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="title" content="Housibly">
<meta name="description" content="Housibly Description">
<meta property="og:type" content="website">
<meta property="og:url" content="index.php">
<meta property="og:title" content="Housibly">
<meta property="og:description" content="Housibly Description">
<meta property="og:image" content="assets/images/thumbnail.jpg">
<meta property="twitter:card" content="thumbnail">
<meta property="twitter:url" content="index.php">
<meta property="twitter:title" content="Housibly">
<meta property="twitter:description" content="Housibly Description">
<meta property="twitter:image" content="assets/images/thumbnail.jpg">

<!-- Css Files -->
<!--<link rel="stylesheet" href="assets/css/bootstrap.min.css?<?php echo time(); ?>">-->
<!--<link rel="stylesheet" href="assets/css/app.min.css?<?php echo time(); ?>">-->
<!--<link rel="stylesheet" href="assets/css/datepicker.min.css?<?php echo time(); ?>">-->

<!-- JS Files -->
<!--<script src="assets/js/jquery.min.js?<?php echo time(); ?>"></script>-->
<!--<script src="assets/js/bootstrap.bundle.min.js?<?php echo time(); ?>"></script>-->
<!--<script src="assets/js/datepicker.min.js?<?php echo time(); ?>"></script>-->

<!-- Favicon -->
<!--<link type="image/png" rel="icon" href="assets/images/favicon.png">-->