config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  mount StripeEvent::Engine, at: '/webhooks'
  root 'dashboards#index'
  resources :supports do
    member do
      get :get_specific_chat
    end
    collection do
      get :update_ticket_status
    end
  end
  resources :sub_admins do
    member do
      get :deactive_admin
      get :active_admin
    end
  end
  resources :school_pins do
    collection do
    get 'get_school_pins'
  end
end
  resources :dashboards do
    post :index
    collection do
      get :notification_page
    end
  end
  resources :support_closers do
    member do
      get :active_account
      get :deactive_account
    end
  end
  resources :guidelines do
    collection do
      post :job_list
      get :job_lists
      delete :job_list
      get :contact_us
      get :privacy_policy
      get :deletion
    end
  end
  get '/delete_job_list/:id', to: 'guidelines#delete_job_list', as: :delete_job_list
  post 'privacy_policy/:permalink', to: 'guidelines#create'
   resources :users_data do
    collection do
      get :buy_vacant_land
      post :buy_vacant_land
      get :buy_house
      post :buy_house
      get :buy_condo
      post :buy_condo
      get :sell_vacant_land
      post :sell_vacant_land
      get :sell_house
      post :sell_house
      get :sell_condo
      post :sell_condo
      get :user_info
      get :dream_address
      get :property_profile
    end
  end
  resources :users_lists do
    member do
      get :active_account
      get :deactive_account
      get :user_profile
    end
  end
  devise_for :admins,
  controllers: {
    passwords: 'admins/passwords'
  }
  get '/sp_active_account/:id', to: 'support_closers#active_user', as: 'sp_active_account'
  get '/sp_deactive_account/:id', to: 'support_closers#deactive_user',as: 'sp_deactive_account'
  get '/privacy_policy/:permalink', to: 'guidelines#guidelines', as: 'privacy_policy'

  namespace :api do
    namespace :v1 do

      post '/login', to: 'sessions#login'
      post '/logout', to: 'sessions#logout'

      post '/signup', to: 'registrations#create'
      post '/register_user', to: 'registrations#complete_registration'
      post '/verify_otp', to: 'registrations#verify_otp'
      post '/verify_otp/resend_otp', to: 'registrations#resend_otp'

      post '/forgot_password/email', to: 'forgot_password#forgot_password_through_email'
      post '/forgot_password/phone', to: 'forgot_password#forgot_password_through_phone'
      post '/reset_password/email', to: 'forgot_password#reset_password_with_email'
      post '/reset_password/phone', to: 'forgot_password#reset_password_with_phone'

      get '/show_profile', to: 'users#show_profile'
      get '/show_other_user_profile', to: 'users#show_other_user_profile'
      get '/profile_visitor_list', to: 'users#profile_visitor_list'
      put '/update_profile', to: 'users#update_profile'
      delete '/delete_account', to: 'users#delete_account'
      get '/search_support_closers', to: 'users#search_support_closers'
      get '/top_support_closers', to: 'users#get_highest_rated_support_closers'
      get 'blocked_users', to: 'users#blocked_users'
      get 'unblocked_users', to: 'users#unblocked_users'
      post 'block_unblock_user', to: 'users#block_unblock_user'
      post 'report_unreport_user', to: 'users#report_unreport_user'
      get 'reported_users', to: 'users#reported_users'
      put '/update_location', to: 'users#update_location'
      # post '/get_school', to: 'users#get_school'
      # post '/get_school_pins', to: 'users#get_school_pins'

      post '/create_card', to: 'payments#create_card'
      get '/get_packages', to: 'payments#get_packages'
      post '/create_package', to: 'payments#create_package'
      post '/create_subscription_on_card', to: 'payments#create_subscription_on_card'
      post '/create_subscription_on_digital_wallet', to: 'payments#create_subscription_on_digital_wallet'
      post '/cancel_subscription', to: 'payments#cancel_subscription'
      get '/get_subscription', to: 'payments#get_subscription'
      get '/get_subscription_history', to: 'payments#get_subscription_history'
      get '/get_card', to: 'payments#get_card'
      get '/get_all_cards', to: 'payments#get_all_cards'
      get '/get_default_card', to: 'payments#get_default_card'
      put '/set_default_card', to: 'payments#set_default_card'
      put '/update_card', to: 'payments#update_card'
      delete '/delete_card', to: 'payments#destroy_card'

      get '/mark_as_read', to: 'notifications#mark_as_read'
      get '/get_user_notifications', to: 'notifications#get_user_notifications'
      delete '/delete_notification', to: 'notifications#delete_notification'

      get '/tickets', to: 'supports#get_tickets'
      post '/tickets', to: 'supports#create_ticket'

      post '/social_login', to: 'social_logins#social_login'
      get '/static_page/:permalink', to: 'static_pages#static_page'
      post '/active', to: 'users_lists#index'

      get '/show_current_user_setting', to: 'user_settings#show'
      put '/update_current_user_setting', to: 'user_settings#update'

      resources :properties, only: [:index, :show, :create, :update, :destroy] do
        collection do
          get :detail_options
          get :matching_properties
          get :buy_properties_listing
          get :find_in_circle
          get :find_in_polygon
          get :find_by_zip_code
          get :details_by_property_id
          # get :recent_properties
          # get :matching_property
          # get :matching_dream_address
        end
      end

      resources :dream_addresses, only: [:index, :create, :destroy]
      # resources :dream_addresses, only: [:index, :create, :destroy] do
      #   collection do
      #     post :fetch_property
      #     post 'fetch_user'
      #   end
      # end

      resources :saved_searches, except: [:new, :edit]
      resources :bookmarks, only: [:index, :create, :destroy]

      resources :user_preferences, only: [:index, :create] do
        collection do
          get '/potential_buyers', to: 'user_preferences#get_potential_buyer_preferences'
        end
      end
      resources :reviews, only: [:create] do
        collection do
          get :get_reviews
        end
      end
      resources :searched_addresses, only: [:create] do
        collection do
          get :get_users
        end
      end
      resources :support_conversations do
        collection do
          post :create_message
          post :get_messages
        end
      end
      resources :reporting do
        collection do
          post 'report_conversation'
        end
      end
      resources :conversations, only: [:create, :index, :destroy] do
        collection do
          post :check_conversation_between_users
          post :check_conversation_blocked_status
          post :read_messages
        end
      end
      resources :messages, only: [:create, :destroy] do
        collection do
          post :get_messages
        end
      end

      get '/*a', to: 'api#not_found'
    end
  end

end

app/controllers/users_data_controller.rb
class UsersDataController < ApplicationController
  def index
    notification = AdminNotification.find_by(id:params[:id])
    notification.update(read_at:Time.now) if notification.present?
    unless params[:search].blank?
      @all_users = User.custom_search(params[:search]).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    else
      @all_users = User.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    end
    response_to_method(@all_users)
  end

  def buy_vacant_land
    @vacant_lands = VacantLand.paginate(page: params[:page], per_page: 10)
    response_to_method(@vacant_lands)
  end

  def sell_vacant_land
    @vacant_lands = VacantLand.paginate(page: params[:page], per_page: 10)
    response_to_method(@vacant_lands)
  end

  def user_info
    @users = User.paginate(page: params[:page], per_page: 10)
    response_to_method(@users)
  end

  def property_profile
    @property = Property.find_by(id: params[:id])

  end

  def dream_address
    @address = DreamAddress.paginate(page: params[:page], per_page: 10)
  end

  def search_dream_address

  end

  def buy_condo
    @condos = Condo.paginate(page: params[:page], per_page: 10)
    response_to_method(@condos)
  end

  def sell_condo
    @condos = Condo.paginate(page: params[:page], per_page: 10)
    response_to_method(@condos)
  end

  def buy_house
    @houses = House.paginate(page: params[:page], per_page: 10)
    response_to_method(@houses)
  end

  def sell_house
    @houses = House.paginate(page: params[:page], per_page: 10)
    response_to_method(@houses)
  end

  private

  def response_to_method(data)
    respond_to do |format|
      format.html
      format.csv { send_data data ? data.to_csv : "Data not found" }
    end
  end
end

app/views/users_data/buy_condo.html.erb
<section id="account_section">
	<%= render 'shared/sidebar' %>
	<div id="buy_house" class="main_side">
		<div id="top_header">
			<h1>Buy Condo</h1>
			<%= render 'shared/header-side' %>
		</div>
		<div class="row">
			<div class="col-6">
				<ul class="top_blk">
					<li>
						<div class="dropdown">
							<button class="filter text dropdown-toggle fs_5 fw_600" data-bs-toggle="dropdown">
								<div class="img_blk">
									<%= image_tag 'filter.svg', alt: '' %>
								</div>
								filters
							</button>
							<%= render 'shared/drop_down' %>
						</div>
					</li>
					<li>
						<div class="form_blk">
							<div class="icon_blk">
								<%= image_tag 'search.svg', alt: '' %>
							</div>
							<input type="search" placeholder="Search" class="input">
						</div>
					</li>
					<li>
						<button type="button" class="filter">
							<div class="img_blk">
								<%= image_tag 'csv-file-icon.svg', alt: '' %>
							</div>
							<%= link_to "Download CSV",buy_condo_users_data_path(format: 'csv', search: params[:search], page: params[:page], checkbox_value:""), id: "downloadbtncustom" %>
						</button>
					</li>
				</ul>
			</div>
		</div>
		<div class="table_blk">
			<table class="mt-5">
				<thead>
					<tr>
						<th style="width: 18.7rem">
							Full Name
						</th>
						<th style="width: 17.2rem">
							Property Type
						</th>
						<th style="width: 20.6rem">
							Price Range
						</th>
						<th style="width: 17.1rem">
							Min Bedrooms
						</th>
						<th style="width: 24.5rem">
							Min Bathrooms
						</th>
						<th style="width: 22.3rem">
							Property Types
						</th>
						<th style="width: 18rem">
							Property Styles
						</th>
						<th style="width: 16rem">
							Living Space
						</th>
						<th style="width: 20.1rem">
							Parking Spots Req.
						</th>
						<th style="width: 12.8rem">
							Balcony
						</th>
						<th style="width: 13rem">
							Security
						</th>
						<th style="width: 13rem">
							Laundry
						</th>
						<th style="width: 13rem">
							Max Age
						</th>
					</tr>
				</thead>
				<tbody>
					<% @condos.each do |condo|%>
					<tr>
						<td><%= condo.user.full_name%></td>
						<td><%= condo.type%></td>
						<td style="color: #00A66C;"><%= condo.price%></td>
						<td><%= condo.bed_rooms%></td>
						<td> <%= condo.bath_rooms%></td>
						<td><%= condo.condo_style%></td>
						<td><%= condo.condo_type %></td>
						<td><%= condo.living_space %></td>
						<td><%= condo.total_parking_spaces %></td>
						<td><% condo.balcony %></td>
						<td><% condo.security%></td>
						<td><% condo.laundry%></td>
						<td>30</td>
					</tr>
					<%end%>
				</tbody>
			</table>
		</div>
		<%= render 'shared/pagination' ,data: @condos%>
	</div>
</section>

app/views/users_data/buy_house.html.erb
<section id="account_section">
  <%= render 'shared/sidebar' %>
  <div id="buy_house" class="main_side">
    <div id="top_header">
      <h1>Buy House</h1>
      <%= render 'shared/header-side' %>
    </div>
    <div class="row">
      <div class="col-6">
        <ul class="top_blk">
          <li>
            <div class="dropdown">
              <button class="filter text dropdown-toggle fs_5 fw_600" data-bs-toggle="dropdown">
                <div class="img_blk">
                  <%= image_tag 'filter.svg', alt: '' %>
                </div>
                filters
              </button>
              <%= render 'shared/drop_down' %>
            </div>
          </li>
          <li>
            <div class="form_blk">
              <div class="icon_blk">
                <%= image_tag 'search.svg', alt: '' %>
              </div>
              <input type="search" placeholder="Search" class="input">
            </div>
          </li>
          <li>
            <button type="button" class="filter">
              <div class="img_blk">
                <%= image_tag 'csv-file-icon.svg', alt: '' %>
              </div>
              <%= link_to "Download CSV",buy_house_users_data_path(format: 'csv', search: params[:search], page: params[:page], checkbox_value:""), id: "downloadbtncustom" %>
            </button>
          </li>
        </ul>
      </div>
    </div>
    <div class="table_blk">
      <table class="mt-5  ">
        <thead>
          <tr>
            <th style="width: 18.7rem">
              Full Name
            </th>
            <th style="width: 17.2rem">
              Property Type
            </th>
            <th style="width: 20.6rem">
              Price Range
            </th>
            <th style="width: 17.1rem">
              Min Bedrooms
            </th>
            <th style="width: 24.5rem">
              Min Bathrooms
            </th>
            <th style="width: 22.3rem">
              Property Types
            </th>
            <th style="width: 18rem">
              Property Styles
            </th>
            <th style="width: 19.1rem">
              Min Lot Forntage
            </th>
            <th style="width: 12.9rem">
              Lot Size
            </th>
            <th style="width: 16rem">
              Living Space
            </th>
            <th style="width: 20.1rem">
              Parking Spots Req.
            </th>
            <th style="width: 19.9rem">
              Garage Spots Req.
            </th>
            <th style="width: 19rem">
              Max Age
            </th>
          </tr>
        </thead>
        <tbody>
          <% @houses.each do |house|%>
          <tr>
            <td><%= house.user.full_name%></td>
            <td><%= house.type%></td>
            <td style="color: #00A66C;"><%= house.price%></td>
            <td><%= house.bed_rooms%></td>
            <td><%= house.bath_rooms%></td>
            <td><%= house.house_type %></td>
            <td><%= house.house_style %></td>
            <td><%= house.lot_frontage%></td>
            <td><%= house.lot_size%></td>
            <td><%= house.living_space %></td>
            <td><%= house.total_parking_spaces %></td>
            <td><%= house.garage_spaces%></td>
            <td><%= house.year_built ? (Time.now.year - house.year_built) : 'N/A' %></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
    <%= render 'shared/pagination' ,data: @houses%>
  </div>
</section>

app/views/users_data/buy_vacant_land.html.erb
  <section id="account_section">
    <%= render 'shared/sidebar' %>
    <div id="buy_house" class="main_side">
      <div id="top_header">
        <h1>Buy Vacant Land</h1>
        <%= render 'shared/header-side' %>
      </div>
      <div class="row">
        <div class="col-6">
          <ul class="top_blk">
            <li>
              <div class="dropdown">
                <button class="filter text dropdown-toggle fs_5 fw_600" data-bs-toggle="dropdown">
                  <div class="img_blk">
                    <%= image_tag 'filter.svg', alt: '' %>
                  </div>
                  filters
                </button>
                <%= render 'shared/drop_down' %>
              </div>
            </li>
            <li>
              <div class="form_blk">
                <div class="icon_blk">
                  <%= image_tag 'search.svg', alt: '' %>
                </div>
                <input type="search" placeholder="Search" class="input">
              </div>
            </li>
            <li>
              <button type="button" class="filter">
                <div class="img_blk">
                  <%= image_tag 'csv-file-icon.svg', alt: '' %>
                </div>
                <%= link_to "Download CSV",buy_vacant_land_users_data_path(format: 'csv', search: params[:search], page: params[:page], checkbox_value:""), id: "downloadbtncustom"%>
              </button>
            </li>
          </ul>
        </div>
      </div>
      <div class="table_blk">
        <table class="mt-5  ">
          <thead>
            <tr>
              <th style="width: 18.7rem">
                Full Name
              </th>
              <th style="width: 17.2rem">
                Property Type
              </th>
              <th style="width: 20.6rem">
                Price Range
              </th>
              <th style="width: 17.1rem">
                Min Lot Frontage
              </th>
              <th style="width: 24.5rem">
                Lot Size
              </th>
            </tr>
          </thead>
          <tbody>
            <% @vacant_lands.each do |vacant_land|%>
            <tr>
              <td class="fw_500 user_name "><%= vacant_land.user.full_name%></td>
              <td><%= vacant_land.type%></td>
              <td style="color: #00A66C;"><%= vacant_land.price%></td>
              <td><%= vacant_land.lot_frontage %></td>
              <td><%= vacant_land.lot_size%></td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
      <%= render 'shared/pagination' ,data: @vacant_lands%>
    </div>
  </section>

app/views/users_data/dream_address.html.erb
<section id="account_section">
  <%= render 'shared/sidebar' %>
  <div id="dream_address" class="main_side">
    <div id="top_header">
      <h1>Dream Address</h1>
      <%= render 'shared/header-side' %>
    </div>
    <div class="row">
      <div class="col-6">
        <ul class="top_blk">
          <li>
            <div class="dropdown">
              <button class="filter text dropdown-toggle fs_5 fw_600" data-bs-toggle="dropdown">
                <div class="img_blk">
                  <%= image_tag 'filter.svg', alt: '' %>
                </div>
                filters
              </button>
              <%= render 'shared/drop_down' %>
            </div>
          </li>
          <li>
            <div class="form_blk">
              <div class="icon_blk">
                <%= image_tag 'search.svg', alt: '' %>
              </div>
              <input type="search" placeholder="Search" class="input">
            </div>
          </li>
          <li>
            <button type="button" class="filter">
              <div class="img_blk">
                <%= image_tag 'csv-file-icon.svg', alt: '' %>
              </div>
              <%= link_to "Download CSV", dream_address_users_data_path(format: 'csv', search: params[:search], page: params[:page], checkbox_value:""), id: "downloadbtncustom"%>
            </button>
          </li>
        </ul>
      </div>
    </div>
    <div class="table_blk">
      <table class="mt-5 w-100 overflow-x-auto ">
        <thead>
        <tr>
          <th style="width: 6rem">
            Full Name
          </th>
          <th style="width: 20rem">
            Dream Address
          </th>
        </tr>
        </thead>
        <tbody>
          <% @address.each do |record| %>
           <tr>
            <td class="fw_500 user_name "><%= record.user.full_name%></td>
            <td class="dream_address">
              <p>
                <%= record.location %>
              </p>
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
    <%= render 'shared/pagination' ,data: @address%>
  </div>
</section>

app/views/users_data/index.html.erb
<main>
  <section id="account_section">
    <%= render 'shared/sidebar' %>
    <div id="buy_house" class="main_side">
      <div id="top_header">
        <h1>User's All Data</h1>
        <%= render 'shared/header-side' %>
      </div>
      <div class="row">
        <div class="col-6">
          <ul class="top_blk">
            <li>
              <div class="dropdown">
                <button class="filter text dropdown-toggle fs_5 fw_600" data-bs-toggle="dropdown">
                  <div class="img_blk">
                    <%= image_tag 'filter.svg', alt: '' %>
                  </div>
                  filters
                </button>
                  <%= render 'shared/drop_down' %>
              </div>
            </li>
            <li>
              <%= form_for :sub_admin, :url => {:controller => 'users_data', :action => 'index'}, :html => {:method => 'get', class: "form_blk"} do |f| %>
                <div class="icon_blk">
                  <%= image_tag 'search.svg' %>
                </div>
                <%= text_field_tag :search, nil, placeholder: 'Search',id: "csearchbtn", class: 'input',value: params[:search]%>
                <input type="submit" id="searchformc" hidden>
              <% end %>
            </li>
            <li>
              <button type="button" class="filter">
                <div class="img_blk">
                  <%= image_tag 'csv-file-icon.svg', alt: '' %>
                </div>
                <%= link_to "Download CSV", users_data_path(format: 'csv', search: params[:search], page: params[:page], checkbox_value:""), id: "downloadbtncustom" %>
              </button>
            </li>
          </ul>
        </div>
      </div>
      <div class="table_blk">
        <table class="mt-5">
          <thead>
          <tr>
            <th style="width: 18.7rem">
              Full Name
            </th>
            <th style="width: 17.2rem">
              Email Address
            </th>
            <th style="width: 20.6rem">
              Phone No.
            </th>
            <th style="width: 17.1rem">
              Real State Agent
            </th>
            <th style="width: 22.5rem">
              Address
            </th>
            <th style="width: 26.3rem">
              Bio
            </th>
          </tr>
          </thead>
          <tbody>
            <% @all_users.each do |user| %>
          <tr>
            <td class="fw_500 user_name " style="padding-right: 30px;">
              <%= link_to user_profile_users_list_path(id: user) do %>
                <%= user.full_name %>
              <%end%>
            </td>
            <td style="padding-right: 40px;"><%= user.email %></td>
            <td style="padding-right: 30px;"><%=user.phone_number%></td>
            <td style="padding-right: 25px;"><%=user.contacted_by_real_estate%></td>
            <td style="padding-right: 55px;"><%=user.address%></td>
            <td style="padding-right: 30px;"><%= user.description %></td>
            
          </tr>
          <%end%>
          </tbody>
        </table>
      </div>
      <%= render 'shared/pagination' ,data:@all_users%>
    </div>
  </section>
</main>

app/views/users_data/sell_vacant_land.html.erb
  <section id="account_section">
    <%= render "shared/sidebar" %>
    <div id="buy_house" class="main_side">
      <div id="top_header">
        <h1>Sell Vacant Land</h1>
        <%= render "shared/header-side" %>
      </div>
      <div class="row">
        <div class="col-6">
          <ul class="top_blk">
            <li>
              <div class="dropdown">
                <button class="filter text dropdown-toggle fs_5 fw_600" data-bs-toggle="dropdown">
                  <div class="img_blk">
                    <%= image_tag 'filter.svg', alt: '' %>
                  </div>
                  filters
                </button>
                <%= render "shared/drop_down" %>
              </div>
            </li>
            <li>
              <div class="form_blk">
                <div class="icon_blk">
                  <%= image_tag 'search.svg', alt: '' %>
                </div>
                <input type="search" placeholder="Search" class="input">
              </div>
            </li>
            <li>
              <button type="button" class="filter">
                <div class="img_blk">
                  <%= image_tag 'csv-file-icon.svg', alt: '' %>
                </div>
                <%= link_to "Download CSV", sell_vacant_land_users_data_path(format: 'csv', search: params[:search], page: params[:page], checkbox_value:""), id: "downloadbtncustom" %>
              </button>
            </li>
          </ul>
        </div>
      </div>
      <div class="table_blk">
        <table class="mt-5  ">
          <thead>
          <tr>
            <th style="width: 18.9rem">
              Full Name
            </th>
            <th style="width: 14.4rem">
              Property Type
            </th>
            <th style="width: 15.2rem">
              Post Title
            </th>
            <th style="width: 14.3rem">
              Asking Price
            </th>
            <th style="width: 26.2rem">
              Street Address
            </th>
            <th style="width: 14.2rem">
              Lot Frontage (ft)
            </th>
            <th style="width: 14.2rem">
              Lot Depth (ft)
            </th>
            <th style="width: 16.1rem">
              Lot Size (ft)
            </th>
            <th style="width: 19.4rem">
              Is Your Lot Irregular
            </th>
            <th style="width: 54.3rem">
              Lot Description
            </th>
            <th style="width: 18.4rem">
              Property Taxes
            </th>
            <th style="width: 12.1rem">
              Tax Year
            </th>
            <th style="width: 50rem">
              Property Description
            </th>
          </tr>
        </thead>
        <tbody>
          <% @vacant_lands.each do |vacant_land|%>
        <tr>
          <td class="fw_500 user_name "><% vacant_land.user.full_name%></td>
          <td><%= vacant_land.type%></td>
          <td><%= vacant_land.title%></td>
          <td style="color: #00A66C;"><%= vacant_land.price%></td>
          <td><%= vacant_land.address%></td>
          <td><%= vacant_land.lot_frontage%></td>
          <td><%= vacant_land.lot_depth%></td>
          <td><%= vacant_land.lot_size%></td>
          <td><%= vacant_land.is_lot_irregular%></td>
          <td><%= vacant_land.lot_description%></td>
          <td><%= vacant_land.property_tax%></td>
          <td><%= vacant_land.tax_year%></td>
          <td><%= vacant_land.property_description%></td>
        </tr>
        <%end%>
        </tbody>
      </table>
    </div>
    <%= render 'shared/pagination' ,data: @vacant_lands%>
  </div>
</section>

app/views/users_data/user_info.html.erb
<main>
  <section id="account_section">
    <%= render 'shared/sidebar' %>
    <div id="user_info" class="main_side">
      <div id="top_header">
        <h1>User Info</h1>
        <%= render 'shared/header-side' %>
      </div>
      <div class="row">
        <div class="col-6">
          <ul class="top_blk">
            <li>
              <div class="dropdown">
                <button class="filter text dropdown-toggle fs_5 fw_600" data-bs-toggle="dropdown">
                  <div class="img_blk">
                    <%= image_tag 'filter.svg', alt: '' %>
                  </div>
                  filters
                </button>
                <%= render 'shared/drop_down' %>
              </div>
            </li>
            <li>
              <%= form_for :sub_admin, :url => {:controller => 'support_closers', :action => 'index'}, :html => {:method => 'get',id: 'searchformc', class: "form_blk"} do |f| %>
                <div class="icon_blk">
                  <%= image_tag 'search.svg' %>
                </div>
                <%= text_field_tag :search,nil, placeholder: 'Search',id: "csearchbtn", class: 'input',value: params[:search]%>
              <% end %>
            </li>
            <li>
              <button type="button" class="filter">
                <div class="img_blk">
                  <%= image_tag 'csv-file-icon.svg', alt: '' %>
                </div>
                <%= link_to "Download CSV",user_info_users_data_path(format: 'csv', search: params[:search], page: params[:page], checkbox_value:""), id: "downloadbtncustom" %>
              </button>
            </li>
          </ul>
        </div>
      </div>
      <div class="table_blk">
        <table class="mt-5">
          <thead>
          <tr>
            <th style="width:18.9rem">
              Full Name
            </th>
            <th style="width: 25.4rem;">
              Email Address
            </th>
            <th style="width:19.8rem">
              Phone No
            </th>
            <th style="width:17.2rem">
              Real State Agent
            </th>
            <th style="width:21.1rem">
              Address
            </th>
            <th style="width: 20rem">
              Bio
            </th>
          </tr>
          </thead>
          <tbody>
            <% @users.each do |user|%>
            <tr>
             <td class="fw_500 user_name ">
               <%= link_to user_profile_users_list_path(id: user) do %>
                 <%= user.full_name%>
                 <%end%>
             </td>
              <td><%= user.email%></td>
              <td><%= user.phone_number%></td>
              <td><%= user.contacted_by_real_estate%></td>
              <td class="address"><%= user.address%></td>
              <td class="bio"><%= user.description%></td>
             </tr>
          <%end%>
          </tbody>
        </table>
      </div>
      <%= render 'shared/pagination' ,data: @users%>
    </div>
  </section>


</main>